# Generated by Django 6.0.2 on 2026-02-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_app', '0002_submission_submission_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='plagiarism_score',
            field=models.FloatField(default=0),
        ),
    ]
